import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import NavBar from '@/app/components/nav-bar/nav-bar'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='h-screen w-screen overflow-hidden'>
      <body className='h-screen w-screen max-h-screen divide-y text-slate-800 grid grid-rows-[1fr_auto]'>
        <div className='bg-slate-100 relative overflow-y-scroll overflow-x-hidden'>
          {children}
        </div>
        <NavBar />
      </body>
    </html>
  )
}
